// Generated by gencpp from file tutorials/mySRV.msg
// DO NOT EDIT!


#ifndef TUTORIALS_MESSAGE_MYSRV_H
#define TUTORIALS_MESSAGE_MYSRV_H

#include <ros/service_traits.h>


#include <tutorials/mySRVRequest.h>
#include <tutorials/mySRVResponse.h>


namespace tutorials
{

struct mySRV
{

typedef mySRVRequest Request;
typedef mySRVResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mySRV
} // namespace tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorials::mySRV > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tutorials::mySRV&) { return value(); }
};

template<>
struct DataType< ::tutorials::mySRV > {
  static const char* value()
  {
    return "tutorials/mySRV";
  }

  static const char* value(const ::tutorials::mySRV&) { return value(); }
};


// service_traits::MD5Sum< ::tutorials::mySRVRequest> should match 
// service_traits::MD5Sum< ::tutorials::mySRV > 
template<>
struct MD5Sum< ::tutorials::mySRVRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorials::mySRV >::value();
  }
  static const char* value(const ::tutorials::mySRVRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorials::mySRVRequest> should match 
// service_traits::DataType< ::tutorials::mySRV > 
template<>
struct DataType< ::tutorials::mySRVRequest>
{
  static const char* value()
  {
    return DataType< ::tutorials::mySRV >::value();
  }
  static const char* value(const ::tutorials::mySRVRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorials::mySRVResponse> should match 
// service_traits::MD5Sum< ::tutorials::mySRV > 
template<>
struct MD5Sum< ::tutorials::mySRVResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorials::mySRV >::value();
  }
  static const char* value(const ::tutorials::mySRVResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorials::mySRVResponse> should match 
// service_traits::DataType< ::tutorials::mySRV > 
template<>
struct DataType< ::tutorials::mySRVResponse>
{
  static const char* value()
  {
    return DataType< ::tutorials::mySRV >::value();
  }
  static const char* value(const ::tutorials::mySRVResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIALS_MESSAGE_MYSRV_H
